version = 1
exclude_patterns = [
  "node_modules",
  "bower_components",
  "out",
  "bin",
  "build",
  "dist",
  "venv",
]
test_patterns = [
  "**/test/**",
  "**/*Test*.java",
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.spec.js",
  "**/*.test.ts",
  "**/*.test.js",
  "**/test_*.py",
]

[[analyzers]]
name = "javascript"
enabled = true
